    <table width="100%" cellpadding="2" border="0" cellspacing="0">
      <tr bgcolor="#aabbcc">
        <td>
          <a href="logout.php" target="_top"><?php echo translate("Logout"); ?></a>
        </td><td align="right">
          <?php echo translate("Current Folder"); ?>: <b><?php echo $current_folder ?></b>
        </td>
      </tr><tr>
        <td>
          <a href="compose.php"><?php echo translate("Compose"); ?></a> &nbsp;
          Addresses &nbsp;
          <a href="folders.php"><?php echo translate("Folders"); ?></a> &nbsp;
          <a href="options.php"><?php echo translate("Options"); ?></a> &nbsp;
          <a href="help.php"><?php echo translate("Help"); ?></a> &nbsp;
        </td><td align="right">
          &nbsp;
        </td>
      </tr>
    </table>
