#!/bin/sh

echo -n "Please enter path to your squirrelmail installation:"
read smpath

cp -i eastasia/*.php ${smpath}/functions/decode
cp -i x-mac/*.php ${smpath}/functions/decode

echo ""
echo "Extra decoding functions are installed."