#!/bin/sh
STRINGS=$1
for trans in `ls locale/`; do
        for string in $STRINGS ; do
        echo -n ${trans}
	echo -n " - "
	echo -n ${string}
        if [ -f locale/${trans}/LC_MESSAGES/${string}.po ] ; then
	    echo " - translation available"
	    msgfmt --statistics locale/${trans}/LC_MESSAGES/${string}.po \
	     -o /dev/null
	else
	    echo " - translation unavailable"
	fi
    done
done
		