#!/bin/sh
if [ -z "$1" ]; then
 echo "USAGE: extract-plugin [pluginname]"
  exit 1
fi
date=`date +%Y%m%d`
install -d packages
plugin=$1
if [ ! -f po/${plugin}.pot ]; then
    echo "No such plugin"
    exit 1
fi
# Compile locales
for trans in `ls locale/`; do
    if [ -f locale/${trans}/LC_MESSAGES/${plugin}.po ]; then
	msgfmt locale/${trans}/LC_MESSAGES/${plugin}.po \
	    -o locale/${trans}/LC_MESSAGES/${plugin}.mo
    fi
done
# Build package
tar -cf packages/${plugin}-${date}.tar \
    locale/*/LC_MESSAGES/${plugin}.po \
    locale/*/LC_MESSAGES/${plugin}.mo \
    po/${plugin}.pot install
zip -q packages/${plugin}-${date}.zip \
    locale/*/LC_MESSAGES/${plugin}.po \
    locale/*/LC_MESSAGES/${plugin}.mo \
    po/${plugin}.pot install
# Pack them
for package in `ls packages/*-${date}.tar`; do
    gzip ${package} -c > ${package}.gz
    bzip2 ${package}
done
#
echo "Plugin translations are saved in packages directory"
