#!/bin/sh
for trans in `ls locale/`; do
    mv locale/${trans}/LC_MESSAGES/squirrelmail.po \
	locale/${trans}/LC_MESSAGES/squirrelmail.po.bak
    msgmerge --no-location locale/${trans}/LC_MESSAGES/squirrelmail.po.bak \
	po/squirrelmail.pot > \
	locale/${trans}/LC_MESSAGES/squirrelmail.po
#    rm locale/${trans}/LC_MESSAGES/squirrelmail.po.bak
done
	  