#!/bin/sh
STRINGS=$1
for trans in `ls locale/`; do
        for string in $STRINGS ; do
        if [ -f locale/${trans}/LC_MESSAGES/${string}.po ] ; then
        echo -n ${trans}
	echo -n " - "
	echo -n ${string}
	    echo " - translation available"
	    msgfmt --statistics locale/${trans}/LC_MESSAGES/${string}.po \
	     -o /dev/null
	fi
    done
done
		