#!/bin/sh
XGETTEXT_OPTIONS="--keyword=_ -keyword=N_ --keyword=ngettext:1,2 --default-domain=smdoc"

# Allows controlling language option
# (gettext v.0.10.40 = -C, gettext 0.11+ = -L php).
if [ $SM_LANG_PHP ] ; then
 XGETTEXT_OPTIONS="${XGETTEXT_OPTIONS} -L php";
else
 XGETTEXT_OPTIONS="${XGETTEXT_OPTIONS} -C";
fi
  

xgettext ${XGETTEXT_OPTIONS} \
    ../*.php --output=smdoc.pot
xgettext ${XGETTEXT_OPTIONS} -j \
    ../lib/*.php --output=smdoc.pot
xgettext ${XGETTEXT_OPTIONS} -j \
    ../lib/input/*.php --output=smdoc.pot
xgettext ${XGETTEXT_OPTIONS} -j \
    ../templates/*.tpl --output=smdoc.pot


