#!/bin/bash
# $1 = version with dots

set -e

if [ -z $1 ]; then
    echo You need to specify the version to be released:
    echo make-release 1.2.2
    exit
fi
dashver=`echo $1 | sed 's/\./_/g'`

echo == Releasing version $1 with tag rel-$dashver ==

echo -- making dir --
rm -rf $1
mkdir $1
echo -- cding to dir --
cd $1
echo -- exporting svn --
svn export https://squirrelmail.svn.sourceforge.net/svnroot/squirrelmail/tags/rel-$dashver \
    squirrelmail-$1
echo -- cding to checkout --
cd squirrelmail-$1
echo -- removing .anything files \(except .ht*\) --
find -iregex '.*/\.[^ht].*'                     -exec rm -rf {} \;
echo -- setting general permissions --
find                                            -exec chmod ugo+r,u+w,go-w {} \;
echo -- setting general file permissions --
find -type f                                    -exec chmod ugo-x {} \;
echo -- setting general directory permissions --
find -type d                                    -exec chmod ugo+x {} \;
echo -- setting perl permissions --
find -name '*.pl'                               -exec chmod ugo+x {} \;
echo -- setting +w on special directories --
chmod ug+w ./data ./config
echo -- setting special file permissions --
chmod ugo+x ./configure ./po/compilepo ./po/mergepo ./po/xgetpo
echo -- cding up --
cd ..
echo -- making .tar.gz --
tar cvf squirrelmail-$1.tar squirrelmail-$1
gzip -9 squirrelmail-$1.tar
md5sum squirrelmail-$1.tar.gz > squirrelmail-$1.tar.gz.md5
sha1sum squirrelmail-$1.tar.gz > squirrelmail-$1.tar.gz.sha1
echo -- making .tar.bz2 --
tar cjvf squirrelmail-$1.tar.bz2 squirrelmail-$1
md5sum squirrelmail-$1.tar.bz2 > squirrelmail-$1.tar.bz2.md5
sha1sum squirrelmail-$1.tar.bz2 > squirrelmail-$1.tar.bz2.sha1
echo -- making .zip --
zip -9 -r squirrelmail-$1.zip squirrelmail-$1
md5sum squirrelmail-$1.zip > squirrelmail-$1.zip.md5
sha1sum squirrelmail-$1.zip > squirrelmail-$1.zip.sha1
echo -- optionally making .rpm s --
rpmbuild -ta squirrelmail-$1.tar.gz || true
echo -- uploading to upload.sf.net --
curl -T squirrelmail-$1.tar.gz -u anonymous:wouter@teepe.com ftp://upload.sf.net/incoming/
curl -T squirrelmail-$1.tar.bz2 -u anonymous:wouter@teepe.com ftp://upload.sf.net/incoming/
curl -T squirrelmail-$1.zip -u anonymous:wouter@teepe.com ftp://upload.sf.net/incoming/
curl -T squirrelmail-$1-1.7.x.noarch.rpm -u anonymous:wouter@teepe.com ftp://upload.sf.net/incoming/
curl -T squirrelmail-$1-1.src.rpm -u anonymous:wouter@teepe.com ftp://upload.sf.net/incoming/
echo -- finished so far --
