<?php
/*
 *  $Id$
 *  $Author$
 *  $Date$
 *
 *  all.inc
 *  This file would basically just be to include the core libs
 *  Should make disgning a controller a little easier
 */
      // include all needed function libs
      // The directory structure is not important for this example
      // I would suggest sq_ to avoid possible
      // name conflicts with other scripts
      // new libs are added here so they are available to the entire
      // core without any other file changes
 
 include("sq.inc");
 include("example.inc");
?>